<?php
namespace MailChimp\Data;

use MailChimp\Core\Data;

/**
 * @property string $type An absolute URI that identifies the problem type. When dereferenced, it should provide human-readable documentation for the problem type.
 * @property string $title A short, human-readable summary of the problem type. It shouldn’t change based on the occurrence of the problem, except for purposes of localization.
 * @property int $status The HTTP status code (RFC2616, Section 6) generated by the origin server for this occurrence of the problem.
 * @property string $detail A human-readable explanation specific to this occurrence of the problem. Learn more about errors.
 * @property string $instance A string that identifies this specific occurrence of the problem. Please provide this ID when contacting support.
 */
class Error extends Data {

  /**
   * @ignore
   */
  protected $fields = [
    'type' => ['type' => 'string', 'required' => true],
    'title' => ['type' => 'string', 'required' => true],
    'status' => ['type' => 'int', 'required' => true],
    'detail' => ['type' => 'string', 'required' => true],
    'instance' => ['type' => 'string', 'required' => true],
    'errors' => ['type' => 'array[]']
  ];

}

